version: '3'

services:
  # Node.js
  frontend:
    build: ./frontend
    container_name: node
    tty: true
    ports:
      - 3000:3000
    # プロジェクトディレクトリにマウントする
    volumes:
      - ./frontend:/app
    command: sh -c "cd muce && npm run dev"
    # ネットワーク
    networks:
      - default

  backend:
    build: ./backend
    tty: true
    volumes:
      - ./backend:/go/src/work
    command: go run server.go
    ports:
      - 1323:1323
    networks:
      - default

  # データベース
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    # working_dirs: /database/
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      # 設定ファイルディレクトリにマウントする
      - ./mysql/conf.d:/etc/mysql/conf.d
      # DB初期化ディレクトリにマウントする
      - ./mysql/init.d:/docker-entrypoint-initdb.d
      - ./mysql/create_table.sql:/database/create_table.sql
    # ネットワーク
    networks:
      - default

# ネットワーク
networks:
  default:
    driver: bridge
