version: '3'

services:
  # Node.js
  frontend:
    build: ./frontend
    container_name: node
    tty: true
    ports:
      - 3000:3000
    stdin_open: true
    # プロジェクトディレクトリにマウントする
    volumes:
      - ./frontend:/app
      # - ./frontend/muce/node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    command: sh -c "cd muce && npm run dev"
    # ネットワーク
    networks:
      - default

# ネットワーク
networks:
  default:
    driver: bridge
